version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: echo srvr | nc localhost 2181 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  user-service:
    build: ./user-service
    env_file: ./user-service/.env
    ports:
      - '3001:3001'
    depends_on:
      - kafka

  book-service:
    build: ./book-service
    env_file: ./book-service/.env
    ports:
      - '3002:3002'
    depends_on:
      - kafka

  loan-service:
    build: ./loan-service
    env_file: ./loan-service/.env
    depends_on:
      - kafka
      - penalty-service
    ports:
      - '3003:3003'

  penalty-service:
    build: ./penalty-service
    env_file: ./penalty-service/.env
    ports:
      - '50051:50051'

  graphql-gateway:
    build: ./graphql-gateway
    env_file: ./graphql-gateway/.env
    ports:
      - '4000:4000'
    depends_on:
      - user-service
      - book-service
      - loan-service
      - penalty-service
